MordechaiHadad/bob

- Cargo.lock
- Cargo.toml
- src/modules/cli.rs
- src/modules/uninstall_handler.rs
Switches arg parsing to the clap-derive API to reduce boilerplate code and simplify the codebase altogether.
A new change: the `ls` subcommand is now called `list`, but has an alias to `ls`, if that's undesired - let me know 😄
> Switch arg parsing to clap-derive

- Cargo.lock
- src/modules/expand_archive.rs
- src/modules/install_handler.rs
> Fix version installation bug for MacOS

- Cargo.lock
- Cargo.toml
- src/modules/cli.rs
- src/modules/expand_archive.rs
- src/modules/use_handler.rs
> change(macos-release): When nvim-osx64 folder is found it will be renamed to nvim-macos

- src/modules/cli.rs
- src/modules/expand_archive.rs
- src/modules/ls_handler.rs
- check for empty installation.
- alias `rm` for the `uninstall` subcommand.
- removed padding for progress on unzipping.
> add check for empty installations, add alias for `uninstall`

- src/main.rs
- src/modules/expand_archive.rs
- src/modules/install_handler.rs
- src/modules/utils.rs
This PR updates codebase to utilize `anyhow` to avoid panicking via `unwrap()` and handles the errors gracefully.
> refactor: improve error handling

- src/modules/install_handler.rs
- src/modules/ls_handler.rs
- src/modules/use_handler.rs
- src/modules/utils.rs
This commit fixes the lints suggested by rust-clippy.
<details>
<summary>Details</summary>
```
error: written amount is not handled
--> src/modules/install_handler.rs:140:29
|
140 | ...                   file.write(&chunk).await?;
|                       ^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: use `AsyncWriteExt::write_all` instead, or handle partial writes
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount
= note: `#[deny(clippy::unused_io_amount)]` on by default
warning: match expression looks like `matches!` macro
--> src/modules/install_handler.rs:182:31
|
182 |                   Err(error) => match error.kind() {
|  _______________________________^
183 | |                     std::io::ErrorKind::NotFound => false,
184 | | …
```
> refactor: apply clippy suggestions

- Cargo.toml
I saw that some information is missing in `Cargo.toml` so I decided to add them via this PR. (They are useful for crates.io release)
> chore(cargo): add metadata to Cargo.toml

- .github/workflows/build.yml
- src/modules/install_handler.rs
- src/modules/utils.rs
This PR integrates `clippy` to CI workflow for checking lints so that issues like #71 can be detected early in the development phase.
> chore(ci): integrate clippy to continuous integration workflow

- README.md
- src/main.rs
- src/models/mod.rs
- src/modules/cli.rs
- src/modules/mod.rs
- src/modules/sync_handler.rs
- src/modules/use_handler.rs
- src/modules/utils.rs
#80 
Using `bob sync` will try to read a version stored at the configured `sync_version_file_path`. This is useful when using version control to track local configurations, where one might want to document when the version of neovim was changed (and to what version).
Note that this **does not** replace the `used` file in the downloads directory, `used` is regarded as the truth on the current installed neovim version, whereas `sync_version_file_path` can have any content, regardless of the current installed version.
> Feature: bob sync (and `sync_version_file_path` config)

- .github/workflows/build.yml
This PR updates the continuous integration workflow to always build with `--locked` flag for making sure that `Cargo.lock` is up-to-date.
It will help spotting issues like #89 early in the development phase.
> Build with `--locked` flag

- src/modules/cli.rs
- src/modules/sync_handler.rs
- src/modules/use_handler.rs
Added the option to opt-out from auto-invoking the install command when switching neovim versions.
This is useful for metered/slow network connections.
Also thanks for this amazing project.
> feat(cli): add `--no-install` flag to the Cli enum

- src/helpers/directories.rs
- this resolves #112
- this uses `create_dir_all` to create even parent directories if it doesnt exist
```rust
let is_folder_created = tokio::fs::create_dir_all(&data_dir).await.is_ok();
```
> Fix: couldn't create downloads directory

- src/main.rs
> Windows: Don't create a cmd window for nvim-qt

- Cargo.lock
- Cargo.toml
- README.md
- src/cli.rs
At first I wanted to generate the completion files at compile time and then `include_str!` them in the binary (so that I could avoid adding yet another dependency), but that brought a lot of complexity into the code base which was completely unnecessary plus it made it impossible to access the `clap_complete::Shell` enum directly in the `Cli` enum.
Anyhow, I can do that if that seems to be a better option.
> feat(cli): add `complete [shell]` subcommand for tab-completion gen

- README.md
- src/cli.rs
- src/handlers/sync_handler.rs
- src/handlers/use_handler.rs
- src/helpers/version/mod.rs
Commit 8e56ea8 renamed `sync_version_file_path` to
`version_sync_file_location`, however some places still refer to the old name.
This is mostly relevant in the README and in the error messages (as `sync_version_file_path needs to be set to use bob sync` is still printed, which uses the wrong name and is quite confusing)
The commit was generated from this command running on MacOS
```bash
find src/**/* -type f | xargs sed -i '' -e 's/sync_version_file_path/version_sync_file_location/g'
```
(and then I also edited the README manually)
> Config: Update all leftover references to sync_version_file_path

- .github/workflows/build-native_tls.yml
- Cargo.lock
- Cargo.toml
- README.md
This addresses issue #140 by enabling the option to compile either with `rustls-tls` (by default) or `native-tls` using feature flags.
> feat(build): enable optional compilation with `native-tls`

- README.md
- src/config.rs
- src/handlers/install_handler.rs
Hey!
Personally I like to compile my nightly builds as a release for performance improvements. For that I have slightly refactored the code to check for this config option and to compile neovim nightly instead of downloading the pre-built binary in case this setting is enabled. It should also work for specific hash installations.
Currently `Make` has issues with those changes and returns the following:
```sh
/Library/Developer/CommandLineTools/usr/bin/make -C build install
[  0%] Built target update_version_stamp
[  4%] Built target nlua0
[ 91%] Built target nvim
[ 91%] Built target nvim_runtime_deps
[100%] Built target translations
[100%] Built target runtime
Install the project...
-- Install configuration: "Release"
Jul 16 22:54:15.055 ERROR Error: No such file or directory (os error 2) …
```
> feat: add release build compilation

- README.md
I moved `bob` to the official repositories: https://archlinux.org/packages/extra/x86_64/bob/
> docs(README): mention that `bob` is an official Arch Linux package

- README.md
- src/cli.rs
resolves MordechaiHadad/bob#157
> Adding support for Github API key #157

- README.md
- src/cli.rs
- src/handlers/uninstall_handler.rs
When there are multiple versions of neovim installed e.g., multiple nightly rollbacks, it can be easier to have a prompt 
so the user can select which versions he wants to uninstall without having to type them one by one. It can also be used for normal uninstalls, which can be helpfull too.
This commit adds a multiselect prompt with all versions that aren't in use when `bob uninstall` is run without arguments:
After selection, it confirms the user's choice and uninstalls the selected neovim versions: 
Thank you very much for this project! This is my first time writing rust so if there are somethings that should be changed please let me know and I will corrected them asap.
> add: uninstall prompt when no version is specified

- src/handlers/uninstall_handler.rs
Use the `non_parsed_string` instead of `tag_name` to allow users to remove nightly rollbacks while on the most recent nightly version.
> fix: use non parsed version string to check if version is used

- src/github_requests.rs
- src/helpers/version/mod.rs
This PR will add `head` and `git` as alias for fetching the latest commit for neovim.
fixes #163
> Add latest commit alias

- README.md
- src/cli.rs
- src/github_requests.rs
- src/handlers/list_remote_handler.rs
- src/handlers/mod.rs
- src/helpers/version/mod.rs
> Add list-remote command

- src/handlers/uninstall_handler.rs
fixes #224 
Let me know what you think!
> Fix: rm/uninstall not working when 'v' is missing for neovim versions.

- Cargo.lock
- Cargo.toml
- src/handlers/install_handler.rs
- src/helpers/checksum.rs
- src/helpers/mod.rs
The checksums are used to make sure you downloaded the complete file and/or it wasn't modified by a third party or a bad connection
> Validate package integrity for non-self-compiled installs

- src/handlers/install_handler.rs
> remove: breaking changes avoidance

- src/handlers/use_handler.rs
- src/helpers/directories.rs
This PR addresses two issues with Windows paths:
1. `AppData/Local` and `AppData/Roaming` were changed to use backslashes instead of forward slashes.
2. When checking if the installation directory has already been added to the path, the paths are normalized by changing forward slashes to backslashes as well as doing a case-insensitive comparison to avoid duplicate paths being added with different casing or slashes.
> fix: fix Windows paths

- README.md
Disabling secure_path is considered unsafe as it allows sudo to run commands from directories that can be modified by any user. I've suggested a safer workaround to get around secure_path without disabling it. Let me know what you think.
> Update README.md troubleshooting section

- src/handlers/list_remote_handler.rs
- src/helpers/mod.rs
After version 0.10.3 neovim added linux arm64, and changed the naming convention for Linux x86_64.
Support for the new Linux arm64 release has also been added.
Fixes #249 
Fixes #250
> fix: support new linux naming convention

- src/cli.rs
In the 4.0.3 release, the root `bob` help output currently looks like this:
```
The `Cli` enum represents the different commands that can be used in the command-line interface
Usage: bob <COMMAND>
Commands:
use          Switch to the specified version, by default will auto-invoke install command if the version is not installed already
install      Install the specified version, can also be used to update out-of-date nightly version
sync         If Config::version_sync_file_location is set, the version in that file will be parsed and installed
uninstall    Uninstall the specified version [aliases: rm]
rollback     Rollback to an existing nightly rollback
erase        Erase any change bob ever made, including neovim installation, neovim version downloads and registry changes
list …
```
> doc(cli): avoid including code comment in help output

- Cargo.toml
Support [`cargo binstall`](https://github.com/cargo-bins/cargo-binstall) by adding the manifest fields to the `Cargo.toml` according to [this documentation](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md). `cargo binstall` reads the manifest to automatically install binaries instead of building. Currently cargo-binstall will install from [quick install](https://github.com/cargo-bins/cargo-quickinstall) which installs incorrect binaries on macos (x86_64 instead of arm).
An alternative to changing the manifest is to change the names of the release artifacts so that it can be automatically detected by `cargo binstall`. Let me know if this is preferred.
Tested by running and verifying architecture with `file`:
- `cargo binstall --force --manifest-path . --root . bob-nvim`, …
> build: add cargo-binstall support

- Cargo.lock
- Cargo.toml
- src/handlers/install_handler.rs
- src/helpers/filesystem.rs
- src/helpers/unarchive.rs
Addressing #298, It looks like the correct fix was to update the offending package to 0.18.0 and fix api calls that styled the progress bar to use the new API around template calls.
Tested with:
```bash
cargo install --git https://github.com/jamesharris-garmin/bob --branch fix-cargo-install
```
which builds and installs correctly.
> Fix cargo install

- Cargo.lock
- Cargo.toml
- src/handlers/use_handler.rs
Closes #321 
Refactor add_to_path for handling non-interactive shells and separate OS logic to compile time
guarded functions.
Changes are mostly the addition of a guard check if we're interactive on either stdout/stderr, wrapping prompt with tokio::time::timeout, and moving the temp config to use a RefCell over cloning.
Currently requires end-user testing, will have to further refactor for mod_tests and proper testing between unix/windows OS's.
> fix(#321): refactor add_to_path + sep. OS logic
