MordechaiHadad/bob

src/modules/install_handler.rs, src/modules/use_handler.rs, src/modules/utils.rs
=> macos-fix: first commit

.github/workflows/build.yml, Cargo.lock, Cargo.toml
=> Create a new bob build for linux systems with different openssl version

.github/workflows/build.yml, Cargo.lock, Cargo.toml
=> fix: include all default features for openssl version

src/modules/install_handler.rs
I think I did it correctly now.
What the title says. This is in addition to your pull request already. I tested it and it works just fine
=> Add CMAKE_BUILD_TYPE and change a CMAKE flag

README.md
fix #51 
before merge the pr please label the pr as `hacktoberfest-accepted`
https://hacktoberfest.com/participation/#spam
=> change options to long format

README.md
- Mentioned AUR package for bob
- Added build prerequisites for Neovim
- Beautified readme by adding icons next to headings
=> docs(README): mention AUR package and add build prerequisites for neovim

README.md
- Added homebrew build instructions for MacOS
- Added Notices section
- Repositioned showcase
=> docs(README): mention macos notes and reposition showcase

README.md, src/modules/install_handler.rs
Found via `typos --format brief`
=> docs: fix typos

README.md
Hello!
I packaged `bob` for Arch Linux in the AUR:
- https://aur.archlinux.org/packages/bob
This PR updates README.md to reflect this 🐻
=> docs(README): mention `bob` AUR package

Cargo.toml
=> change[cargo.toml] Change crate name so it can be uploaded to crates.io

src/main.rs
=> Add env vars for config paths

.github/workflows/build.yml
Not tested this, but I am hopeful that this is all that might be needed to build aarch64-linux binaries for M1!
=> Add aarch64-unknown-linux-gnu build

Cargo.lock, Cargo.toml, README.md, src/main.rs, src/modules/fs.rs, src/modules/utils.rs
=> fix: allow using proxy exe with sudo

src/helpers/directories.rs
=> fix: cfg!(linux) / cfg!(macos)

Cargo.lock, Cargo.toml, src/handlers/install_handler.rs, src/helpers/version/mod.rs, src/helpers/version/types.rs
=> Fix nightly not updating

src/handlers/install_handler.rs
=> fix: creating bob.json for nightly

.dockerignore, Cargo.lock, Cargo.toml, Dockerfile, src/handlers/sync_handler.rs, src/helpers/version/mod.rs
=> Fix sync command

src/handlers/use_handler.rs, src/main.rs
=> Add nvim-qt proxy exe

Cargo.lock, Cargo.toml, src/helpers/version/mod.rs
=> Fix installing via stable chooses the wrong json entry

src/helpers/directories.rs
=> fallback to $HOME if $SUDO_USER and $USER don't work

Cargo.lock, Cargo.toml, src/helpers/unarchive.rs
=> Fix osx64 content from pasting in parent directory

src/helpers/version/mod.rs
=> change: cut the commit hash to only 7 characters

src/main.rs
no reason to redeclare args collection per block expression
=> moved args collection outside of if block

src/handlers/install_handler.rs
=> fix: dont rely on relative path to create bob.json

src/helpers/mod.rs
=> Add support for download arm macos binaries

src/handlers/use_handler.rs
Bring back checking if neovim proxy exists, fixes #198 and possibly #197
=> check if neovim proxy exists

src/handlers/install_handler.rs
=> Build `RelWithDebugInfo` on windows when building neovim from source

Cargo.lock, Cargo.toml, src/handlers/use_handler.rs, src/main.rs
=> Change: neovim proxy auto updater

Cargo.lock, Cargo.toml, README.md, src/handlers/install_handler.rs, src/handlers/use_handler.rs, src/helpers/mod.rs, src/helpers/processes.rs, src/main.rs
=> Handle USR1 kill signal on UNIX

src/handlers/erase_handler.rs
=> Erase only bob associated directories.

Cargo.lock, README.md, src/handlers/install_handler.rs, src/handlers/use_handler.rs, src/helpers/processes.rs, src/helpers/version/mod.rs
=> Use full commit hash for files

Cargo.lock, Cargo.toml
=> Change to rustls native certificate store

src/handlers/install_handler.rs
debug info
more debug info
..... corrected if statement
remove debug statement, i need to squash these commits
=> change: skip checksum matching for ver 0.4.4 and below

Cargo.lock, Cargo.toml, src/handlers/install_handler.rs, src/helpers/checksum.rs
=> Fix checksum compatibility

src/handlers/install_handler.rs, src/handlers/mod.rs, src/helpers/version/types.rs
=> Fix nightly nonsense

Cargo.lock, Cargo.toml, src/cli.rs, src/helpers/processes.rs
=> Check if neovim is running before executing some commands

Cargo.lock, src/handlers/use_handler.rs
=> Better error handling when modifying rc files fails

src/handlers/list_remote_handler.rs
=> Handle broken pipe error when listing remote versions

README.md, src/cli.rs, src/config.rs
=> FEAT: add ignore_running_instances configuration option

.deepsource.toml, Cargo.toml, src/cli.rs, src/config.rs, src/consts.rs, src/github_requests.rs, src/handlers/erase_handler.rs, src/handlers/install_handler.rs, src/handlers/list_handler.rs, src/handlers/rollback_handler.rs, src/handlers/sync_handler.rs, src/handlers/uninstall_handler.rs, src/handlers/update_handler.rs, src/handlers/use_handler.rs, src/helpers/checksum.rs, src/helpers/directories.rs, src/helpers/filesystem.rs, src/helpers/mod.rs, src/helpers/processes.rs, src/helpers/unarchive.rs, src/helpers/version/mod.rs, src/helpers/version/nightly.rs, src/main.rs
This PR introduces significant performance improvements and code quality enhancements through regex compilation optimization, code de-duplication, and some minor structural refactoring.
The changes move repeatedly compiled regex patterns to compile-time constants and implement several architectural improvements.
Aimed to keep the revset fairly small to make it easy to review, let me know if it's a bit much much.
- Replaced runtime Regex::new() calls with static `LazyLock<Regex>` patterns
- Implemented `EnvVarProcessor` trait for cleaner environment variable handling
- Consolidated platform-specific file extension logic into compile-time constants
- Mild improvements to error handling patterns and reduced code duplication
Perf. Optimizations
- Regex compilation: Moved all regex patterns …
=> Regex cleanup

src/config.rs, src/github_requests.rs, src/handlers/erase_handler.rs, src/handlers/install_handler.rs, src/handlers/rollback_handler.rs, src/helpers/directories.rs, src/helpers/version/types.rs
PR adds additional docs to public API's and corrects a handful of small grammatical errors and doc-linting warnings.
- src/config.rs
- src/github_requests.rs
- src/handlers/erase_handler.rs
- src/handlers/install_handler.rs
- src/helpers/directories.rs
- src/helpers/version/types.rs
- Public API documentation additions make understanding functionality easier.
- Improved readability in some areas.
- Grammatical corrections.
=> [DOCS]: Additional docs and small grammatical fixes
